/**
 * Master Prompt Generator — converts a compiled DAG into a single
 * comprehensive system prompt describing the full workflow logic.
 */

import type { PipelineNode, PipelineEdge } from "../types";
import { compileGraph } from "./graphCompiler";
import { getNodeDefinition } from "../nodes/definitions";

export function generateMasterPrompt(
  nodes: PipelineNode[],
  edges: PipelineEdge[],
  workflowName = "Aura Workflow"
): string {
  const { plan } = compileGraph(nodes, edges);
  const nodeMap = new Map(nodes.map((n) => [n.id, n]));

  const triggers = plan.steps.filter((s) => {
    const def = getNodeDefinition(s.nodeType);
    return def?.category === "trigger";
  });

  const aiNodes = plan.steps.filter((s) => {
    const def = getNodeDefinition(s.nodeType);
    return def?.category === "ai";
  });

  const integrations = plan.steps.filter((s) => {
    const def = getNodeDefinition(s.nodeType);
    return def?.category === "endpoint" || def?.category === "messaging" || def?.category === "db";
  });

  // Build step descriptions
  const stepDescriptions = plan.steps
    .map((step, i) => {
      const node = nodeMap.get(step.nodeId);
      const def = getNodeDefinition(step.nodeType);
      const config = node?.data?.config ?? {};

      let desc = `${i + 1}. **${step.nodeLabel}** (${def?.label ?? step.nodeType})`;

      if (step.inputs.length > 0) {
        const inputLabels = step.inputs.map((id) => {
          const n = nodeMap.get(id);
          return String(n?.data?.label ?? id);
        });
        desc += `\n   - Receives input from: ${inputLabels.join(", ")}`;
      }

      if (Object.keys(config).length > 0) {
        const configStr = Object.entries(config)
          .filter(([, v]) => v !== undefined && v !== "")
          .slice(0, 3)
          .map(([k, v]) => `${k}=${String(v).slice(0, 40)}`)
          .join(", ");
        if (configStr) desc += `\n   - Config: ${configStr}`;
      }

      if (step.outputs.length > 0) {
        const outputLabels = step.outputs.map((id) => {
          const n = nodeMap.get(id);
          return String(n?.data?.label ?? id);
        });
        desc += `\n   - Sends output to: ${outputLabels.join(", ")}`;
      }

      return desc;
    })
    .join("\n\n");

  const triggerDesc =
    triggers.length > 0
      ? triggers.map((t) => `- ${t.nodeLabel} (${t.nodeType})`).join("\n")
      : "- Manual trigger";

  const aiDesc =
    aiNodes.length > 0
      ? aiNodes.map((a) => {
          const node = nodeMap.get(a.nodeId);
          const model = String(node?.data?.model ?? node?.data?.config?.model ?? "gpt-4o");
          const sys = String(node?.data?.systemPrompt ?? node?.data?.config?.systemPrompt ?? "");
          return `- ${a.nodeLabel}: model=${model}${sys ? `, system="${sys.slice(0, 80)}..."` : ""}`;
        }).join("\n")
      : "- No AI nodes";

  const integrationDesc =
    integrations.length > 0
      ? integrations.map((i) => `- ${i.nodeLabel} (${i.nodeType})`).join("\n")
      : "- No external integrations";

  return `# ${workflowName} — Master System Prompt
Generated by Aura Engine on ${new Date().toLocaleDateString()}

## Overview
This is a ${nodes.length}-node, ${edges.length}-edge automated workflow.
Estimated tokens per run: ~${plan.totalEstimatedTokens.toLocaleString()}
Estimated cost per run: ${plan.estimatedCostUSD < 0.001 ? "< $0.001" : "$" + plan.estimatedCostUSD.toFixed(4)}

## Triggers
${triggerDesc}

## AI Components
${aiDesc}

## External Integrations
${integrationDesc}

## Execution Flow (${plan.steps.length} steps)

${stepDescriptions}

## System Instructions

You are an automated pipeline orchestrator executing the "${workflowName}" workflow. Follow these rules:

1. Process each step in the order listed above.
2. Pass the output of each step as the input to the next step(s).
3. If a step fails, apply the retry policy (default: 3 retries with exponential backoff).
4. Log all significant events with timestamps.
5. For AI steps: use the specified model and temperature. Respect the system prompt.
6. For integration steps: use the provided credentials. Handle rate limits gracefully.
7. For conditional steps (IF/Switch): evaluate the condition and route accordingly.
8. Return the final output in the format specified by the Output node.

## Environment Variables Required
${plan.steps
  .flatMap((s) => {
    const def = getNodeDefinition(s.nodeType);
    return (def?.requiredCredentials ?? []).map(
      (c) => `${s.nodeLabel.toUpperCase().replace(/\s+/g, "_")}_${c.key.toUpperCase()}=<${c.label}>`
    );
  })
  .filter((v, i, a) => a.indexOf(v) === i) // dedupe
  .join("\n") || "# No credentials required"}

---
*This prompt was auto-generated by Aura Engine. Review and customize before production deployment.*`;
}
