/**
 * ZIP Exporter — generates a runnable project ZIP from the compiled workflow.
 * Uses JSZip to produce a downloadable archive with:
 * frontend/, backend/, bot/, shared/, package.json, .env.template,
 * README.md, start.sh, docker-compose.yml, workflow.json
 */

import JSZip from "jszip";
import type { PipelineNode, PipelineEdge, ExportProjectType } from "../types";
import { compileGraph } from "./graphCompiler";
import { getNodeDefinition } from "../nodes/definitions";
import { generateMasterPrompt } from "./masterPromptGenerator";

// ── Collect required env vars from workflow ───────────────────────────────────
function collectEnvVars(nodes: PipelineNode[]): Record<string, string> {
  const env: Record<string, string> = {};
  for (const node of nodes) {
    const def = getNodeDefinition(node.data.nodeType ?? "");
    if (!def?.requiredCredentials) continue;
    for (const cred of def.requiredCredentials) {
      const key = `${(node.data.label ?? node.data.nodeType ?? node.id)
        .toUpperCase()
        .replace(/\s+/g, "_")}_${cred.key.toUpperCase()}`;
      env[key] = cred.secret ? "" : "your_value_here";
    }
  }
  return env;
}

// ── File generators ───────────────────────────────────────────────────────────
function genEnvTemplate(envVars: Record<string, string>): string {
  const lines = [
    "# Aura Engine — Environment Variables",
    "# Copy this file to .env and fill in your values",
    "",
    "# App Config",
    "PORT=3000",
    "NODE_ENV=development",
    "",
    "# AI Keys",
    "OPENAI_API_KEY=sk-...",
    "ANTHROPIC_API_KEY=sk-ant-...",
    "GEMINI_API_KEY=AIza...",
    "",
    "# Workflow-specific credentials",
    ...Object.entries(envVars).map(([k, v]) => `${k}=${v || "<fill_in>"}`),
  ];
  return lines.join("\n");
}

function genReadme(
  workflowName: string,
  projectType: ExportProjectType,
  masterPrompt: string
): string {
  return `# ${workflowName}

Generated by [Aura Engine](https://auraflow.dev) — Visual AI Workflow Orchestrator.

## Project Type
${projectType}

## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Copy and fill environment variables
cp .env.template .env
# Edit .env with your API keys and credentials

# Start development server
npm run dev
\`\`\`

## Docker

\`\`\`bash
# Build and start with Docker Compose
docker-compose up --build

# Stop
docker-compose down
\`\`\`

## Project Structure

\`\`\`
├── frontend/        React SPA with workflow UI
├── backend/         Node.js API server
├── bot/             Bot scaffolding (if applicable)
├── shared/          Shared types and utilities
├── workflow.json    Aura workflow definition
├── .env.template    Required environment variables
└── docker-compose.yml
\`\`\`

## Workflow

${masterPrompt}

---
*Built with Aura Engine v1.0*
`;
}

function genStartScript(): string {
  return `#!/bin/bash
set -e

echo "🚀 Starting Aura Engine Workflow App..."

# Check for .env
if [ ! -f .env ]; then
  echo "⚠️  .env not found. Copying from template..."
  cp .env.template .env
  echo "✏️  Please fill in your credentials in .env then re-run this script."
  exit 1
fi

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Start all services
echo "▶️  Starting services..."
if command -v concurrently &> /dev/null; then
  concurrently "npm run dev:backend" "npm run dev:frontend"
else
  npm run dev
fi
`;
}

function genDockerCompose(workflowName: string): string {
  const name = workflowName.toLowerCase().replace(/\s+/g, "-");
  return `version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

  # Uncomment for PostgreSQL support
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: ${name}
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   pgdata:
`;
}

function genBackendIndex(workflowJson: string): string {
  return `const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json());

// ── Workflow definition ──────────────────────────────────────────────────────
const workflow = ${workflowJson};

// ── Health check ─────────────────────────────────────────────────────────────
app.get('/health', (req, res) => {
  res.json({ status: 'ok', workflow: workflow.nodes?.length + ' nodes' });
});

// ── Webhook trigger ───────────────────────────────────────────────────────────
app.post('/webhook', async (req, res) => {
  console.log('[Webhook] Received:', JSON.stringify(req.body).slice(0, 200));
  try {
    const result = await executeWorkflow(req.body);
    res.json({ success: true, result });
  } catch (err) {
    console.error('[Webhook] Error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

// ── Workflow executor (stub — add your logic here) ────────────────────────────
async function executeWorkflow(input) {
  console.log('[Engine] Executing workflow with', workflow.nodes.length, 'nodes');
  // TODO: Implement actual node execution based on workflow.json
  // Each node type maps to a handler function
  return { message: 'Workflow executed', input };
}

// ── Start server ─────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(\`✅ Aura Engine Backend running on port \${PORT}\`);
});
`;
}

function genFrontendApp(): string {
  return `import React, { useState } from 'react';

function App() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);

  const runWorkflow = async () => {
    setLoading(true);
    try {
      const res = await fetch('/webhook', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input }),
      });
      const data = await res.json();
      setOutput(JSON.stringify(data, null, 2));
    } catch (err) {
      setOutput('Error: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: 32, fontFamily: 'sans-serif', maxWidth: 800 }}>
      <h1>🌐 Aura Workflow Runner</h1>
      <textarea
        value={input}
        onChange={e => setInput(e.target.value)}
        placeholder="Enter input JSON or text..."
        rows={6}
        style={{ width: '100%', marginBottom: 12, fontFamily: 'monospace' }}
      />
      <button onClick={runWorkflow} disabled={loading} style={{ padding: '8px 24px', marginBottom: 24 }}>
        {loading ? 'Running...' : '▶ Run Workflow'}
      </button>
      {output && (
        <pre style={{ background: '#f5f5f5', padding: 16, borderRadius: 8, overflow: 'auto' }}>
          {output}
        </pre>
      )}
    </div>
  );
}

export default App;
`;
}

function genBotIndex(botType: ExportProjectType, workflowJson: string): string {
  if (botType === "telegram-bot") {
    return `const TelegramBot = require('node-telegram-bot-api');
require('dotenv').config();

const workflow = ${workflowJson};
const bot = new TelegramBot(process.env.BOT_TOKEN, { polling: true });

bot.on('message', async (msg) => {
  const chatId = msg.chat.id;
  const text = msg.text;

  console.log(\`[Telegram] Message from \${msg.from.username}: \${text}\`);

  try {
    // TODO: Execute workflow with msg as input
    const response = \`Received: \${text}\\n\\nWorkflow has \${workflow.nodes.length} nodes configured.\`;
    await bot.sendMessage(chatId, response, { parse_mode: 'Markdown' });
  } catch (err) {
    console.error('[Bot] Error:', err.message);
    await bot.sendMessage(chatId, '❌ An error occurred.');
  }
});

console.log('🤖 Telegram Bot started');
`;
  }

  if (botType === "discord-bot") {
    return `const { Client, GatewayIntentBits } = require('discord.js');
require('dotenv').config();

const workflow = ${workflowJson};
const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent]
});

client.on('ready', () => {
  console.log(\`🤖 Discord Bot logged in as \${client.user.tag}\`);
});

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;

  try {
    // TODO: Execute workflow with message as input
    await message.reply(\`✅ Workflow triggered (${workflowJson.slice(0,20)}...)\`);
  } catch (err) {
    console.error('[Bot] Error:', err.message);
    await message.reply('❌ An error occurred.');
  }
});

client.login(process.env.DISCORD_BOT_TOKEN);
`;
  }

  return `// Bot scaffolding for ${botType}\nconsole.log('Bot starting...');\n`;
}

// ── Main export function ──────────────────────────────────────────────────────
export async function exportProjectZip(
  nodes: PipelineNode[],
  edges: PipelineEdge[],
  projectType: ExportProjectType,
  workflowName = "Aura Workflow"
): Promise<void> {
  const zip = new JSZip();
  const { plan } = compileGraph(nodes, edges);

  const workflowJson = JSON.stringify({ nodes, edges, plan }, null, 2);
  const envVars = collectEnvVars(nodes);
  const masterPrompt = generateMasterPrompt(nodes, edges, workflowName);
  const slugName = workflowName.toLowerCase().replace(/\s+/g, "-");

  // ── Root files ──────────────────────────────────────────────────────────────
  zip.file("workflow.json", workflowJson);
  zip.file(".env.template", genEnvTemplate(envVars));
  zip.file("README.md", genReadme(workflowName, projectType, masterPrompt));
  zip.file("master-prompt.txt", masterPrompt);
  zip.file("start.sh", genStartScript());
  zip.file("docker-compose.yml", genDockerCompose(workflowName));

  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: slugName,
        version: "1.0.0",
        description: `Generated by Aura Engine — ${workflowName}`,
        scripts: {
          dev: "concurrently \"npm run dev:backend\" \"npm run dev:frontend\"",
          "dev:backend": "cd backend && node index.js",
          "dev:frontend": "cd frontend && npm run dev",
          build: "cd frontend && npm run build",
          start: "node backend/index.js",
        },
        dependencies: {
          express: "^4.18.0",
          cors: "^2.8.5",
          dotenv: "^16.0.0",
          concurrently: "^8.0.0",
          ...(projectType === "telegram-bot" ? { "node-telegram-bot-api": "^0.64.0" } : {}),
          ...(projectType === "discord-bot" ? { "discord.js": "^14.0.0" } : {}),
          ...(projectType === "whatsapp-bot" ? { twilio: "^4.0.0" } : {}),
        },
      },
      null,
      2
    )
  );

  // ── Backend ─────────────────────────────────────────────────────────────────
  const backend = zip.folder("backend")!;
  backend.file("index.js", genBackendIndex(workflowJson));
  backend.file(
    "package.json",
    JSON.stringify({ name: `${slugName}-backend`, version: "1.0.0", main: "index.js", scripts: { start: "node index.js", dev: "nodemon index.js" }, dependencies: { express: "^4.18.0", cors: "^2.8.5", dotenv: "^16.0.0" } }, null, 2)
  );
  backend.file(
    "Dockerfile",
    `FROM node:20-alpine\nWORKDIR /app\nCOPY package.json .\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["node", "index.js"]`
  );

  // ── Frontend ────────────────────────────────────────────────────────────────
  const frontend = zip.folder("frontend")!;
  frontend.file("src/App.jsx", genFrontendApp());
  frontend.file("src/main.jsx", `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.jsx';\n\nReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);`);
  frontend.file("index.html", `<!DOCTYPE html>\n<html>\n<head><meta charset="UTF-8"><title>${workflowName}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body>\n</html>`);
  frontend.file("package.json", JSON.stringify({ name: `${slugName}-frontend`, version: "1.0.0", type: "module", scripts: { dev: "vite", build: "vite build" }, dependencies: { react: "^18.2.0", "react-dom": "^18.2.0" }, devDependencies: { "@vitejs/plugin-react": "^4.2.0", vite: "^5.0.0" } }, null, 2));
  frontend.file("vite.config.js", `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({ plugins: [react()], server: { proxy: { '/webhook': 'http://localhost:3000' } } });`);
  frontend.file(
    "Dockerfile",
    `FROM node:20-alpine\nWORKDIR /app\nCOPY package.json .\nRUN npm install\nCOPY . .\nEXPOSE 5173\nCMD ["npm", "run", "dev", "--", "--host"]`
  );

  // ── Bot (if applicable) ─────────────────────────────────────────────────────
  if (["telegram-bot", "discord-bot", "whatsapp-bot"].includes(projectType)) {
    const bot = zip.folder("bot")!;
    bot.file("index.js", genBotIndex(projectType, workflowJson));
    bot.file("package.json", JSON.stringify({ name: `${slugName}-bot`, version: "1.0.0", scripts: { start: "node index.js" } }, null, 2));
  }

  // ── Shared ──────────────────────────────────────────────────────────────────
  const shared = zip.folder("shared")!;
  shared.file(
    "workflow-types.ts",
    `// Auto-generated workflow types\nexport const WORKFLOW_NAME = '${workflowName}';\nexport const NODE_COUNT = ${nodes.length};\nexport const EDGE_COUNT = ${edges.length};\n`
  );

  // ── Download ────────────────────────────────────────────────────────────────
  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slugName}-aura-export.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
