/**
 * ZIP Exporter — generates runnable starter projects from a workflow graph.
 */

import JSZip from "jszip";
import { getNodeDefinition } from "../nodes/definitions";
import type { ExportProjectType, PipelineEdge, PipelineNode } from "../types";
import { compileGraph } from "./graphCompiler";
import { generateMasterPrompt } from "./masterPromptGenerator";

const BOT_PROJECT_TYPES: ExportProjectType[] = [
  "telegram-bot",
  "discord-bot",
  "whatsapp-bot",
];

function lines(parts: string[]): string {
  return `${parts.join("\n")}\n`;
}

function slugify(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function collectEnvVars(
  nodes: PipelineNode[],
  projectType: ExportProjectType,
): Record<string, string> {
  const env: Record<string, string> = {
    PORT: "3000",
    NODE_ENV: "development",
    OPENAI_API_KEY: "",
    ANTHROPIC_API_KEY: "",
    GEMINI_API_KEY: "",
  };

  if (projectType === "fullstack-docker" || projectType === "react-spa") {
    env.VITE_API_URL = "http://localhost:3000";
  }

  if (projectType === "telegram-bot") {
    env.TELEGRAM_BOT_TOKEN = "";
    env.BACKEND_URL = "http://localhost:3000";
  }

  if (projectType === "discord-bot") {
    env.DISCORD_BOT_TOKEN = "";
    env.BACKEND_URL = "http://localhost:3000";
  }

  if (projectType === "whatsapp-bot") {
    env.TWILIO_ACCOUNT_SID = "";
    env.TWILIO_AUTH_TOKEN = "";
    env.TWILIO_WHATSAPP_NUMBER = "whatsapp:+14155238886";
    env.BACKEND_URL = "http://localhost:3000";
    env.BOT_PORT = "3100";
  }

  if (projectType === "wordpress-plugin") {
    env.WP_BRIDGE_API_KEY = "";
  }

  for (const node of nodes) {
    const def = getNodeDefinition(node.data.nodeType ?? "");
    if (!def?.requiredCredentials) continue;
    for (const cred of def.requiredCredentials) {
      const key = `${(node.data.label ?? node.data.nodeType ?? node.id)
        .toUpperCase()
        .replace(/\s+/g, "_")}_${cred.key.toUpperCase()}`;
      env[key] = cred.secret ? "" : "your_value_here";
    }
  }

  return env;
}

function genEnvTemplate(envVars: Record<string, string>): string {
  return lines([
    "# Aura Engine Environment Variables",
    "# Copy this file to .env and fill your values",
    "",
    ...Object.entries(envVars).map(([k, v]) => `${k}=${v}`),
  ]);
}

function projectLabel(projectType: ExportProjectType): string {
  switch (projectType) {
    case "telegram-bot":
      return "Telegram Bot";
    case "discord-bot":
      return "Discord Bot";
    case "whatsapp-bot":
      return "WhatsApp Bot";
    case "react-spa":
      return "React SPA";
    case "node-api":
      return "Node API";
    case "fullstack-docker":
      return "Fullstack Docker";
    case "wordpress-plugin":
      return "WordPress Plugin";
    default:
      return projectType;
  }
}

function genReadme(
  workflowName: string,
  projectType: ExportProjectType,
  masterPrompt: string,
): string {
  const isBot = BOT_PROJECT_TYPES.includes(projectType);
  const includesFrontend =
    projectType === "react-spa" || projectType === "fullstack-docker";
  const includesBackend = projectType !== "react-spa";
  const includesWordPress = projectType === "wordpress-plugin";

  const structure = ["workflow.json", ".env.template", "master-prompt.txt"];
  if (includesBackend) structure.push("backend/");
  if (includesFrontend) structure.push("frontend/");
  if (isBot) structure.push("bot/");
  if (includesWordPress) structure.push("wordpress-plugin/");

  const nextSteps: string[] = ["cp .env.template .env", "npm install", "npm run dev"];
  if (projectType === "fullstack-docker" || isBot) {
    nextSteps.push("docker-compose up --build");
  }
  if (projectType === "wordpress-plugin") {
    nextSteps.push(
      "Install plugin from wordpress-plugin/ in your WordPress instance",
    );
  }

  return lines([
    `# ${workflowName}`,
    "",
    "Generated by Aura Engine visual workflow orchestrator.",
    "",
    "## Project Type",
    projectLabel(projectType),
    "",
    "## Quick Start",
    "```bash",
    ...nextSteps,
    "```",
    "",
    "## Project Structure",
    "```",
    ...structure.map((entry) => `- ${entry}`),
    "```",
    "",
    "## Master Prompt",
    "```text",
    masterPrompt,
    "```",
  ]);
}

function genStartScript(projectType: ExportProjectType): string {
  const runCmd = BOT_PROJECT_TYPES.includes(projectType)
    ? 'concurrently "npm run dev:backend" "npm run dev:bot"'
    : projectType === "fullstack-docker"
      ? 'concurrently "npm run dev:backend" "npm run dev:frontend"'
      : projectType === "react-spa"
        ? "npm run dev:frontend"
        : "npm run dev:backend";

  return lines([
    "#!/bin/bash",
    "set -e",
    "",
    "echo \"Starting exported Aura project...\"",
    "",
    "if [ ! -f .env ]; then",
    "  cp .env.template .env",
    "  echo \"Created .env from template. Fill credentials and rerun.\"",
    "  exit 1",
    "fi",
    "",
    "npm install",
    runCmd,
  ]);
}

function genDockerCompose(
  workflowName: string,
  projectType: ExportProjectType,
): string {
  const name = slugify(workflowName) || "aura-workflow";

  if (projectType === "fullstack-docker") {
    return lines([
      "version: '3.8'",
      "",
      "services:",
      "  backend:",
      "    build:",
      "      context: ./backend",
      "      dockerfile: Dockerfile",
      "    ports:",
      "      - \"3000:3000\"",
      "    env_file:",
      "      - .env",
      "",
      "  frontend:",
      "    build:",
      "      context: ./frontend",
      "      dockerfile: Dockerfile",
      "    ports:",
      "      - \"5173:5173\"",
      "    depends_on:",
      "      - backend",
      "    env_file:",
      "      - .env",
      "",
      "  # Optional database",
      "  # db:",
      "  #   image: postgres:16-alpine",
      "  #   environment:",
      `  #     POSTGRES_DB: ${name}`,
      "  #     POSTGRES_USER: user",
      "  #     POSTGRES_PASSWORD: password",
    ]);
  }

  if (BOT_PROJECT_TYPES.includes(projectType)) {
    return lines([
      "version: '3.8'",
      "",
      "services:",
      "  backend:",
      "    build:",
      "      context: ./backend",
      "      dockerfile: Dockerfile",
      "    ports:",
      "      - \"3000:3000\"",
      "    env_file:",
      "      - .env",
      "",
      "  bot:",
      "    build:",
      "      context: ./bot",
      "      dockerfile: Dockerfile",
      "    env_file:",
      "      - .env",
      "    depends_on:",
      "      - backend",
      ...(projectType === "whatsapp-bot" ? ["    ports:", "      - \"3100:3100\""] : []),
    ]);
  }

  return "";
}

function genBackendIndex(workflowJson: string): string {
  return lines([
    "const express = require('express');",
    "const cors = require('cors');",
    "const { GoogleGenAI } = require('@google/genai');",
    "require('dotenv').config();",
    "",
    "const app = express();",
    "app.use(cors());",
    "app.use(express.json());",
    "",
    "const workflow = " + workflowJson + ";",
    "",
    "const GEMINI_MODELS = ['gemini-3.0-flash', 'gemini-2.5-flash-preview-04-17', 'gemini-1.5-flash'];",
    "const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';",
    "const GEMINI_CLIENT = GEMINI_API_KEY ? new GoogleGenAI({ apiKey: GEMINI_API_KEY }) : null;",
    "",
    "app.get('/health', (_req, res) => {",
    "  res.json({ status: 'ok', nodes: workflow.nodes?.length ?? 0, edges: workflow.edges?.length ?? 0 });",
    "});",
    "",
    "app.get('/workflow', (_req, res) => {",
    "  res.json({ nodes: workflow.nodes, edges: workflow.edges, plan: workflow.plan });",
    "});",
    "",
    "app.post(['/webhook', '/run'], async (req, res) => {",
    "  try {",
    "    const result = await executeWorkflow(req.body ?? {});",
    "    res.json({ success: true, result });",
    "  } catch (err) {",
    "    const message = err instanceof Error ? err.message : 'Workflow execution failed';",
    "    res.status(500).json({ success: false, error: message });",
    "  }",
    "});",
    "",
    "function nodeById(id) {",
    "  return (workflow.nodes || []).find((n) => n.id === id);",
    "}",
    "",
    "function incomingFor(nodeId) {",
    "  return (workflow.edges || []).filter((e) => e.target === nodeId).map((e) => e.source);",
    "}",
    "",
    "async function callGemini(prompt) {",
    "  if (!GEMINI_CLIENT) return { text: prompt, model: null, fallback: true, reason: 'No GEMINI_API_KEY' };",
    "",
    "  for (const model of GEMINI_MODELS) {",
    "    try {",
    "      const response = await GEMINI_CLIENT.models.generateContent({",
    "        model,",
    "        contents: [{ role: 'user', parts: [{ text: prompt }] }],",
    "        config: { temperature: 0.5, maxOutputTokens: 1024 }",
    "      });",
    "      const text = response?.text ?? '';",
    "      if (text) return { text, model, fallback: false };",
    "    } catch (_e) {",
    "      // try next fallback",
    "    }",
    "  }",
    "",
    "  return { text: prompt, model: null, fallback: true, reason: 'All Gemini models failed' };",
    "}",
    "",
    "function safeString(value) {",
    "  if (value == null) return '';",
    "  if (typeof value === 'string') return value;",
    "  try { return JSON.stringify(value); } catch { return String(value); }",
    "}",
    "",
    "function evalCondition(condition, input, context) {",
    "  try {",
    "    const fn = new Function('input', 'context', 'return Boolean(' + condition + ');');",
    "    return Boolean(fn(input, context));",
    "  } catch (_e) {",
    "    return false;",
    "  }",
    "}",
    "",
    "async function executeNode(node, input, context) {",
    "  const nodeType = String(node?.data?.nodeType || node?.type || '').toLowerCase();",
    "  const config = node?.data?.config || {};",
    "",
    "  if (nodeType.includes('trigger') || nodeType === 'custominput' || nodeType === 'webhook' || nodeType === 'timer') return input;",
    "",
    "  if (nodeType === 'if' || nodeType === 'filter') {",
    "    const condition = String(config.condition || node?.data?.condition || 'true');",
    "    return { passed: evalCondition(condition, input, context), input };",
    "  }",
    "",
    "  if (nodeType === 'http' || nodeType === 'api') {",
    "    const url = String(config.url || node?.data?.url || '');",
    "    const method = String(config.method || node?.data?.method || 'GET').toUpperCase();",
    "    if (!url) return { error: 'Missing URL', input };",
    "",
    "    const response = await fetch(url, {",
    "      method,",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: method === 'GET' ? undefined : JSON.stringify(input)",
    "    });",
    "    const text = await response.text();",
    "    try {",
    "      return JSON.parse(text);",
    "    } catch (_e) {",
    "      return text;",
    "    }",
    "  }",
    "",
    "  if (nodeType === 'llm' || nodeType === 'aiagent' || nodeType === 'ragpipeline') {",
    "    const promptBase = config.prompt || node?.data?.prompt || node?.data?.systemPrompt || 'Process workflow input';",
    "    const prompt = String(promptBase) + '\\n\\nINPUT:\\n' + safeString(input);",
    "    return await callGemini(prompt);",
    "  }",
    "",
    "  if (nodeType === 'prompttemplate' || nodeType === 'text') {",
    "    const template = String(config.template || node?.data?.text || node?.data?.prompt || '');",
    "    return { text: template, input };",
    "  }",
    "",
    "  if (nodeType === 'set' || nodeType === 'transform') {",
    "    return { ...(typeof input === 'object' && input ? input : {}), ...(typeof config === 'object' && config ? config : {}) };",
    "  }",
    "",
    "  return input;",
    "}",
    "",
    "async function executeWorkflow(input) {",
    "  const results = {};",
    "  const steps = Array.isArray(workflow.plan?.steps)",
    "    ? workflow.plan.steps.map((s) => s.nodeId)",
    "    : (workflow.nodes || []).map((n) => n.id);",
    "",
    "  for (const nodeId of steps) {",
    "    const node = nodeById(nodeId);",
    "    if (!node) continue;",
    "",
    "    const incoming = incomingFor(nodeId);",
    "    const nodeInput = incoming.length === 0",
    "      ? input",
    "      : incoming.length === 1",
    "        ? results[incoming[0]]",
    "        : incoming.reduce((acc, key) => ({ ...acc, [key]: results[key] }), {});",
    "",
    "    results[nodeId] = await executeNode(node, nodeInput, { input, results, workflow });",
    "  }",
    "",
    "  const lastNodeId = steps[steps.length - 1];",
    "  return {",
    "    output: lastNodeId ? results[lastNodeId] : input,",
    "    results,",
    "  };",
    "}",
    "",
    "const PORT = process.env.PORT || 3000;",
    "app.listen(PORT, () => {",
    "  console.log('Aura backend running on port ' + PORT);",
    "});",
  ]);
}

function genFrontendApp(): string {
  return lines([
    "import React, { useState } from 'react';",
    "",
    "function App() {",
    "  const [input, setInput] = useState('{\"input\":\"hello\"}');",
    "  const [output, setOutput] = useState('');",
    "  const [loading, setLoading] = useState(false);",
    "",
    "  const runWorkflow = async () => {",
    "    setLoading(true);",
    "    try {",
    "      let parsed = {};",
    "      try { parsed = JSON.parse(input); } catch (_e) { parsed = { input }; }",
    "      const res = await fetch('/run', {",
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    "        body: JSON.stringify(parsed),",
    "      });",
    "      const data = await res.json();",
    "      setOutput(JSON.stringify(data, null, 2));",
    "    } catch (err) {",
    "      setOutput('Error: ' + (err instanceof Error ? err.message : String(err)));",
    "    } finally {",
    "      setLoading(false);",
    "    }",
    "  };",
    "",
    "  return (",
    "    <div style={{ padding: 32, fontFamily: 'sans-serif', maxWidth: 860, margin: '0 auto' }}>",
    "      <h1>Aura Workflow Runner</h1>",
    "      <p>Run your exported workflow using backend endpoint /run.</p>",
    "      <textarea",
    "        value={input}",
    "        onChange={(e) => setInput(e.target.value)}",
    "        rows={7}",
    "        style={{ width: '100%', marginBottom: 12, fontFamily: 'monospace' }}",
    "      />",
    "      <button onClick={runWorkflow} disabled={loading} style={{ padding: '8px 24px', marginBottom: 24 }}>",
    "        {loading ? 'Running...' : 'Run Workflow'}",
    "      </button>",
    "      {output && (",
    "        <pre style={{ background: '#0f172a', color: '#e2e8f0', padding: 16, borderRadius: 8, overflow: 'auto' }}>",
    "          {output}",
    "        </pre>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "export default App;",
  ]);
}

function genBotIndex(botType: ExportProjectType): string {
  if (botType === "telegram-bot") {
    return lines([
      "const TelegramBot = require('node-telegram-bot-api');",
      "require('dotenv').config();",
      "",
      "const token = process.env.TELEGRAM_BOT_TOKEN || process.env.BOT_TOKEN;",
      "const backendUrl = (process.env.BACKEND_URL || 'http://localhost:3000').replace(/\\/+$, '');",
      "if (!token) throw new Error('Missing TELEGRAM_BOT_TOKEN');",
      "",
      "const bot = new TelegramBot(token, { polling: true });",
      "",
      "bot.on('message', async (msg) => {",
      "  if (!msg.text) return;",
      "  const chatId = msg.chat.id;",
      "",
      "  try {",
      "    const res = await fetch(backendUrl + '/webhook', {",
      "      method: 'POST',",
      "      headers: { 'Content-Type': 'application/json' },",
      "      body: JSON.stringify({ text: msg.text, chat: msg.chat, from: msg.from }),",
      "    });",
      "    const data = await res.json();",
      "    const output = data?.result?.output ?? data?.result ?? data;",
      "    const text = typeof output === 'string' ? output : JSON.stringify(output, null, 2);",
      "    await bot.sendMessage(chatId, text.slice(0, 3900));",
      "  } catch (err) {",
      "    const message = err instanceof Error ? err.message : String(err);",
      "    await bot.sendMessage(chatId, 'Workflow error: ' + message);",
      "  }",
      "});",
      "",
      "console.log('Telegram bot started');",
    ]);
  }

  if (botType === "discord-bot") {
    return lines([
      "const { Client, GatewayIntentBits } = require('discord.js');",
      "require('dotenv').config();",
      "",
      "const token = process.env.DISCORD_BOT_TOKEN;",
      "const backendUrl = (process.env.BACKEND_URL || 'http://localhost:3000').replace(/\\/+$, '');",
      "if (!token) throw new Error('Missing DISCORD_BOT_TOKEN');",
      "",
      "const client = new Client({",
      "  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent],",
      "});",
      "",
      "client.on('ready', () => {",
      "  console.log('Discord bot logged in as ' + client.user.tag);",
      "});",
      "",
      "client.on('messageCreate', async (message) => {",
      "  if (message.author.bot) return;",
      "",
      "  try {",
      "    const res = await fetch(backendUrl + '/webhook', {",
      "      method: 'POST',",
      "      headers: { 'Content-Type': 'application/json' },",
      "      body: JSON.stringify({ text: message.content, user: message.author.username, channel: message.channelId }),",
      "    });",
      "    const data = await res.json();",
      "    const output = data?.result?.output ?? data?.result ?? data;",
      "    const text = typeof output === 'string' ? output : JSON.stringify(output, null, 2);",
      "    await message.reply(text.slice(0, 1800));",
      "  } catch (err) {",
      "    const msg = err instanceof Error ? err.message : String(err);",
      "    await message.reply('Workflow error: ' + msg);",
      "  }",
      "});",
      "",
      "client.login(token);",
    ]);
  }

  if (botType === "whatsapp-bot") {
    return lines([
      "const express = require('express');",
      "const twilio = require('twilio');",
      "require('dotenv').config();",
      "",
      "const app = express();",
      "const backendUrl = (process.env.BACKEND_URL || 'http://localhost:3000').replace(/\\/+$, '');",
      "const port = Number(process.env.BOT_PORT || 3100);",
      "",
      "app.use(express.urlencoded({ extended: false }));",
      "",
      "app.get('/health', (_req, res) => {",
      "  res.json({ status: 'ok' });",
      "});",
      "",
      "app.post('/twilio/webhook', async (req, res) => {",
      "  const incoming = req.body.Body || '';",
      "  const from = req.body.From || '';",
      "  const twiml = new twilio.twiml.MessagingResponse();",
      "",
      "  try {",
      "    const response = await fetch(backendUrl + '/webhook', {",
      "      method: 'POST',",
      "      headers: { 'Content-Type': 'application/json' },",
      "      body: JSON.stringify({ text: incoming, from }),",
      "    });",
      "    const data = await response.json();",
      "    const output = data?.result?.output ?? data?.result ?? data;",
      "    const text = typeof output === 'string' ? output : JSON.stringify(output, null, 2);",
      "    twiml.message(text.slice(0, 1500));",
      "  } catch (err) {",
      "    const msg = err instanceof Error ? err.message : String(err);",
      "    twiml.message('Workflow error: ' + msg);",
      "  }",
      "",
      "  res.type('text/xml').send(twiml.toString());",
      "});",
      "",
      "app.listen(port, () => {",
      "  console.log('WhatsApp bot webhook listening on port ' + port);",
      "});",
    ]);
  }

  return lines(["console.log('Bot starting...');"]);
}

function genWordPressPlugin(workflowName: string): {
  pluginMain: string;
  readme: string;
} {
  const safeName = workflowName.replace(/'/g, "");

  const pluginMain = lines([
    "<?php",
    "/**",
    ` * Plugin Name: Aura Workflow Bridge - ${safeName}`,
    " * Description: Bridge WordPress to Aura backend webhook endpoint.",
    " * Version: 1.0.0",
    " */",
    "",
    "if (!defined('ABSPATH')) { exit; }",
    "",
    "class Aura_Workflow_Bridge {",
    "  const OPTION_ENDPOINT = 'aura_workflow_endpoint';",
    "  const OPTION_API_KEY = 'aura_workflow_api_key';",
    "",
    "  public function __construct() {",
    "    add_action('admin_menu', array($this, 'menu'));",
    "    add_action('admin_init', array($this, 'settings'));",
    "    add_action('rest_api_init', array($this, 'routes'));",
    "  }",
    "",
    "  public function menu() {",
    "    add_options_page('Aura Workflow Bridge', 'Aura Workflow', 'manage_options', 'aura-workflow-bridge', array($this, 'page'));",
    "  }",
    "",
    "  public function settings() {",
    "    register_setting('aura_workflow_bridge', self::OPTION_ENDPOINT);",
    "    register_setting('aura_workflow_bridge', self::OPTION_API_KEY);",
    "  }",
    "",
    "  public function routes() {",
    "    register_rest_route('aura/v1', '/run', array(",
    "      'methods' => 'POST',",
    "      'callback' => array($this, 'run'),",
    "      'permission_callback' => '__return_true',",
    "    ));",
    "  }",
    "",
    "  public function run($request) {",
    "    $endpoint = get_option(self::OPTION_ENDPOINT, 'http://localhost:3000/webhook');",
    "    $apiKey = get_option(self::OPTION_API_KEY, '');",
    "    $payload = $request->get_json_params();",
    "",
    "    $headers = array('Content-Type' => 'application/json');",
    "    if (!empty($apiKey)) { $headers['Authorization'] = 'Bearer ' . $apiKey; }",
    "",
    "    $response = wp_remote_post($endpoint, array(",
    "      'headers' => $headers,",
    "      'body' => wp_json_encode($payload),",
    "      'timeout' => 20,",
    "    ));",
    "",
    "    if (is_wp_error($response)) {",
    "      return new WP_Error('aura_bridge_error', $response->get_error_message(), array('status' => 500));",
    "    }",
    "",
    "    $body = wp_remote_retrieve_body($response);",
    "    return rest_ensure_response(json_decode($body, true));",
    "  }",
    "",
    "  public function page() {",
    "    ?>",
    "    <div class=\"wrap\"><h1>Aura Workflow Bridge</h1>",
    "    <form method=\"post\" action=\"options.php\">",
    "      <?php settings_fields('aura_workflow_bridge'); ?>",
    "      <table class=\"form-table\">",
    "        <tr><th>Webhook Endpoint</th><td><input class=\"regular-text\" type=\"url\" name=\"<?php echo esc_attr(self::OPTION_ENDPOINT); ?>\" value=\"<?php echo esc_attr(get_option(self::OPTION_ENDPOINT, 'http://localhost:3000/webhook')); ?>\" /></td></tr>",
    "        <tr><th>API Key</th><td><input class=\"regular-text\" type=\"text\" name=\"<?php echo esc_attr(self::OPTION_API_KEY); ?>\" value=\"<?php echo esc_attr(get_option(self::OPTION_API_KEY, '')); ?>\" /></td></tr>",
    "      </table>",
    "      <?php submit_button(); ?>",
    "    </form>",
    "    </div>",
    "    <?php",
    "  }",
    "}",
    "",
    "new Aura_Workflow_Bridge();",
  ]);

  const readme = lines([
    `# Aura WordPress Bridge — ${safeName}`,
    "",
    "This plugin forwards WordPress REST requests to your exported Aura backend webhook.",
    "",
    "## Install",
    "1. Copy this folder to wp-content/plugins/",
    "2. Activate plugin in WordPress admin",
    "3. Configure endpoint under Settings -> Aura Workflow",
    "",
    "## Endpoint",
    "`POST /wp-json/aura/v1/run`",
  ]);

  return { pluginMain, readme };
}

function rootScriptsFor(projectType: ExportProjectType): Record<string, string> {
  const scripts: Record<string, string> = {};

  const includeFrontend =
    projectType === "react-spa" || projectType === "fullstack-docker";
  const includeBackend = projectType !== "react-spa";
  const includeBot = BOT_PROJECT_TYPES.includes(projectType);

  if (includeBackend) {
    scripts["dev:backend"] = "cd backend && npm run dev";
    scripts["start:backend"] = "cd backend && npm run start";
  }
  if (includeFrontend) {
    scripts["dev:frontend"] = "cd frontend && npm run dev";
    scripts["build:frontend"] = "cd frontend && npm run build";
  }
  if (includeBot) {
    scripts["dev:bot"] = "cd bot && npm run dev";
    scripts["start:bot"] = "cd bot && npm run start";
  }

  if (includeBackend && includeFrontend) {
    scripts.dev = "concurrently \"npm run dev:backend\" \"npm run dev:frontend\"";
  } else if (includeBackend && includeBot) {
    scripts.dev = "concurrently \"npm run dev:backend\" \"npm run dev:bot\"";
  } else if (includeBackend) {
    scripts.dev = "npm run dev:backend";
  } else {
    scripts.dev = "npm run dev:frontend";
  }

  if (includeFrontend) {
    scripts.build = "npm run build:frontend";
  }

  scripts.start = includeBackend ? "npm run start:backend" : "npm run dev:frontend";

  return scripts;
}

function rootDependenciesFor(projectType: ExportProjectType): Record<string, string> {
  const deps: Record<string, string> = {
    dotenv: "^16.0.0",
  };

  if (projectType === "fullstack-docker" || BOT_PROJECT_TYPES.includes(projectType)) {
    deps.concurrently = "^8.0.0";
  }

  if (projectType === "telegram-bot") {
    deps["node-telegram-bot-api"] = "^0.64.0";
  }
  if (projectType === "discord-bot") {
    deps["discord.js"] = "^14.0.0";
  }
  if (projectType === "whatsapp-bot") {
    deps.express = "^4.18.0";
    deps.twilio = "^4.0.0";
  }

  return deps;
}

export async function exportProjectZip(
  nodes: PipelineNode[],
  edges: PipelineEdge[],
  projectType: ExportProjectType,
  workflowName = "Aura Workflow",
): Promise<void> {
  const zip = new JSZip();
  const { plan } = compileGraph(nodes, edges);

  const workflowJson = JSON.stringify({ nodes, edges, plan }, null, 2);
  const envVars = collectEnvVars(nodes, projectType);
  const masterPrompt = generateMasterPrompt(nodes, edges, workflowName);
  const slugName = slugify(workflowName) || "aura-workflow";

  const includeFrontend =
    projectType === "react-spa" || projectType === "fullstack-docker";
  const includeBackend = projectType !== "react-spa";
  const includeBot = BOT_PROJECT_TYPES.includes(projectType);

  // Root files
  zip.file("workflow.json", `${workflowJson}\n`);
  zip.file(".env.template", genEnvTemplate(envVars));
  zip.file("README.md", genReadme(workflowName, projectType, masterPrompt));
  zip.file("master-prompt.txt", `${masterPrompt}\n`);
  zip.file("start.sh", genStartScript(projectType));

  const compose = genDockerCompose(workflowName, projectType);
  if (compose) {
    zip.file("docker-compose.yml", compose);
  }

  zip.file(
    "package.json",
    JSON.stringify(
      {
        name: slugName,
        version: "1.0.0",
        description: `Generated by Aura Engine - ${workflowName}`,
        scripts: rootScriptsFor(projectType),
        dependencies: rootDependenciesFor(projectType),
      },
      null,
      2,
    ),
  );

  // Backend
  if (includeBackend) {
    const backend = zip.folder("backend");
    if (!backend) throw new Error("Could not create backend folder");

    backend.file("index.js", genBackendIndex(workflowJson));
    backend.file(
      "package.json",
      JSON.stringify(
        {
          name: `${slugName}-backend`,
          version: "1.0.0",
          main: "index.js",
          scripts: { start: "node index.js", dev: "nodemon index.js" },
          dependencies: {
            "@google/genai": "^1.43.0",
            express: "^4.18.0",
            cors: "^2.8.5",
            dotenv: "^16.0.0",
          },
          devDependencies: {
            nodemon: "^3.1.0",
          },
        },
        null,
        2,
      ),
    );

    backend.file(
      "Dockerfile",
      lines([
        "FROM node:20-alpine",
        "WORKDIR /app",
        "COPY package.json .",
        "RUN npm install",
        "COPY . .",
        "EXPOSE 3000",
        "CMD [\"node\", \"index.js\"]",
      ]),
    );
  }

  // Frontend
  if (includeFrontend) {
    const frontend = zip.folder("frontend");
    if (!frontend) throw new Error("Could not create frontend folder");

    frontend.file("src/App.jsx", genFrontendApp());
    frontend.file(
      "src/main.jsx",
      lines([
        "import React from 'react';",
        "import ReactDOM from 'react-dom/client';",
        "import App from './App.jsx';",
        "",
        "ReactDOM.createRoot(document.getElementById('root')).render(",
        "  <React.StrictMode>",
        "    <App />",
        "  </React.StrictMode>",
        ");",
      ]),
    );

    frontend.file(
      "index.html",
      lines([
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        "  <meta charset=\"UTF-8\">",
        `  <title>${workflowName}</title>`,
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        "</head>",
        "<body>",
        "  <div id=\"root\"></div>",
        "  <script type=\"module\" src=\"/src/main.jsx\"></script>",
        "</body>",
        "</html>",
      ]),
    );

    frontend.file(
      "package.json",
      JSON.stringify(
        {
          name: `${slugName}-frontend`,
          version: "1.0.0",
          type: "module",
          scripts: { dev: "vite", build: "vite build" },
          dependencies: { react: "^18.2.0", "react-dom": "^18.2.0" },
          devDependencies: { "@vitejs/plugin-react": "^4.2.0", vite: "^5.0.0" },
        },
        null,
        2,
      ),
    );

    frontend.file(
      "vite.config.js",
      lines([
        "import { defineConfig } from 'vite';",
        "import react from '@vitejs/plugin-react';",
        "",
        "export default defineConfig({",
        "  plugins: [react()],",
        "  server: {",
        "    proxy: {",
        "      '/webhook': 'http://localhost:3000',",
        "      '/run': 'http://localhost:3000',",
        "      '/workflow': 'http://localhost:3000',",
        "    },",
        "  },",
        "});",
      ]),
    );

    frontend.file(
      "Dockerfile",
      lines([
        "FROM node:20-alpine",
        "WORKDIR /app",
        "COPY package.json .",
        "RUN npm install",
        "COPY . .",
        "EXPOSE 5173",
        "CMD [\"npm\", \"run\", \"dev\", \"--\", \"--host\"]",
      ]),
    );
  }

  // Bot
  if (includeBot) {
    const bot = zip.folder("bot");
    if (!bot) throw new Error("Could not create bot folder");

    bot.file("index.js", genBotIndex(projectType));
    bot.file(
      "package.json",
      JSON.stringify(
        {
          name: `${slugName}-bot`,
          version: "1.0.0",
          scripts: { start: "node index.js", dev: "node index.js" },
          dependencies: {
            ...(projectType === "telegram-bot"
              ? { "node-telegram-bot-api": "^0.64.0" }
              : {}),
            ...(projectType === "discord-bot" ? { "discord.js": "^14.0.0" } : {}),
            ...(projectType === "whatsapp-bot"
              ? { express: "^4.18.0", twilio: "^4.0.0" }
              : {}),
            dotenv: "^16.0.0",
          },
        },
        null,
        2,
      ),
    );
    bot.file(
      "Dockerfile",
      lines([
        "FROM node:20-alpine",
        "WORKDIR /app",
        "COPY package.json .",
        "RUN npm install",
        "COPY . .",
        "CMD [\"node\", \"index.js\"]",
      ]),
    );
  }

  if (projectType === "wordpress-plugin") {
    const plugin = zip.folder("wordpress-plugin");
    if (!plugin) throw new Error("Could not create wordpress-plugin folder");

    const slug = `${slugName}-aura-bridge`;
    const pluginFolder = plugin.folder(slug);
    if (!pluginFolder) throw new Error("Could not create plugin folder");

    const wp = genWordPressPlugin(workflowName);
    pluginFolder.file(`${slug}.php`, wp.pluginMain);
    pluginFolder.file("README.md", wp.readme);
  }

  // Shared metadata
  const shared = zip.folder("shared");
  if (!shared) throw new Error("Could not create shared folder");
  shared.file(
    "workflow-types.ts",
    lines([
      "// Auto-generated workflow types",
      `export const WORKFLOW_NAME = '${workflowName.replace(/'/g, "\\'")}';`,
      `export const NODE_COUNT = ${nodes.length};`,
      `export const EDGE_COUNT = ${edges.length};`,
      `export const PROJECT_TYPE = '${projectType}';`,
    ]),
  );

  // Download
  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slugName}-aura-export.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
